name: Close Stale PRs
on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:30am UTC https://crontab.guru/#30_1_*_*_*
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-pr-stale: 14
          stale-pr-message: 'This PR is stale because it has been open for 14 days.'
          stale-pr-label: 'stale'
          ignore-pr-updates: true
          remove-pr-stale-when-updated: true
          days-before-pr-close: 28
          close-pr-label: 'stale-auto-closed'
          close-pr-message: 'This PR has been closed due to being open for 28 days. Feel free to reopen if you are still interested in this change.'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,wip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
